version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_example
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0.13
    container_name: mysql_example
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
    ports:
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_example
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel:
